Вопросы и ответы
Глава 9. Обработка исключений.

    1. Какой класс находится на вершине иерархии исключений?

     1. 

    2. Объясните вкратце, как используются ключевые слова try и catch?

     2. 

    3. Какая ошибка допущена в приведенном ниже фрагменте кода?

       // ...
       vals[18] = 10;
       catch (ArrayIndexOutOfBoundsException exc) {
           // обработать ошибку
       }

     3. 

    4. Что произойдет, если исключение не будет перехвачено?

     4. 

    5. Какая ошибка допущена в приведенном ниже фрагменте кода?

       class A extends Exception { ...

       class B extends A { ...

       // ...

       try {
           // ...
       }
       catch (A exc) { ... }
       catch (B exc) { ... }

     5. 

    6. Может ли внутренний блок catch повторно генерировать исключение, которое
       будет обработано во внешнем блоке catch?

     6. 

    7. Блок finally - последний фрагмент кода, выполняемый перед зывершением
       программы. Верно или неверно? Обоснуйте свой ответ.

     7. 

    8. Исключения какого типа необходимо явно объявлять с помощью оператора
       throws, включаемого в объявление метода?

     8. 

    9. Какая ошибка допущена в приведенном ниже фрагменте кода?

       class MyClass { // ... }
       // ...
       throw new MyClass();

     9. 

    10. Отвечая на вопрос 3 упражнения для самопроверки по материалу главы 6, вы
        создали класс Stack. Добавьте в него специальные исключения, реагирующие 
        на попытку поместить элемент в переполненный стек и извлечь элемент из 
        пустого стека.

     10. 

    11. Назовите три причины, по которым могут генерироваться исключения.

     11. 

    12. Назовите два непосредственных подкласса Throwable.

     12. 

    13. Что такое групповой перехват исключения?

     13. 

    14. Следует ли перехватывать в программе исключения типа Error?

     14. 